services:
  ejabberd:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ejabberd_xmpp:latest
    container_name: ejabberd
    environment:
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - VHOST=${VHOST}
    volumes:
      - ./ejabberd.yml:/home/ejabberd/conf/ejabberd.yml:ro
    ports:
      - "${PORT_C2S}:5222"
      - "${PORT_S2S}:5269"
      - "${PORT_HTTP}:5280"
      - "${PORT_HTTP_TLS}:5443"
    networks:
      - ejabberd-net

networks:
  ejabberd-net:
    driver: bridge
