services:
  ejabberd:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ejabberd_xmpp:latest
    container_name: ejabberd
    environment:
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - VHOST=${VHOST}
    volumes:
      - ./ejabberd.yml:/home/ejabberd/conf/ejabberd.yml:ro
    ports:
      - "${PORT_C2S}:5222"
      - "${PORT_S2S}:5269"
      - "${PORT_HTTP}:5280"
      - "${PORT_HTTP_TLS}:5443"
    networks:
      - ejabberd-net

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: chat_service
    volumes:
      - mongo-data:/data/db
    networks:
      - ejabberd-net

volumes:
  mongo-data:

networks:
  ejabberd-net:
    driver: bridge
